// const HSED = {
//   "completed": {
//     "TABE": {},
//     "GED.com account": {},
//     "Career Assessment": {},
//     "Orientation": {},
//     "ROI": {},
//     "HS Transcript": {},
//     "Employability": {},
//     "Health": {},
//     "Civics": {},
//     "RLA": {},
//     "Social Studies": {},
//     "Science": {},
//     "Math": {},
//     "17-16": {},
//     "Journey Letter": {}
//   }}

const HSED = {
  "completed": [
    "TABE",
    "GED.com account",
    "Career Assessment",
    "Orientation",
    "ROI",
    "HS Transcript",
    "Employability",
    "Health",
    "Civics",
    "RLA",
    "Social Studies",
    "Science",
    "Math",
    "17-16",
    "Journey Letter"
  ]}

export const newQuestions = {
  "adult": {
    "referred to": {
      "NWTC": {HSED},
      "Western Tech": {HSED},
      "LTC": {HSED},
      "WTC": {HSED},
      "NCTC": {HSED},
      "BTC": {HSED},
      "FVTC (Fox Valley Tech)": {HSED},
      "Mid-State": {HSED},
      "MATC (Madison College)": {HSED},
      "Omega School": {HSED},
      "Northwoods Tech": {HSED},
      "Oneida Community Educational Center": {},
      "Medford Adult Diploma Academy": {},
      "ADVOCAP": {},
      "ADRC": {},
      "Kahoot.com": {},
      "ESL": {},
      "Test Prep Champions": {},
      "HSED": {
        "completed": {
          "TABE": {},
          "GED.com account": {},
          "Career Assessment": {},
          "Orientation": {},
          "ROI": {},
          "HS Transcript": {},
          "Employability": {},
          "Health": {},
          "Civics": {},
          "RLA": {},
          "Social Studies": {},
          "Science": {},
          "Math": {},
          "17-16": {},
          "Journey Letter": {}
        }
      },
      "GED": {
        "completed": [
          "GED Ready - RLA",
          "GED Ready - Social Studies",
          "GED Ready - Science",
          "GED Ready - Math",
          "GED - TABE",
          "GED - GED.com account",
          "GED - Career Assessment",
          "GED - Orientation",
          "GED - ROI",
          "GED - Civics",
          "GED - RLA",
          "GED - Social Studies",
          "GED - Science",
          "GED - Math"
        ]
      }
    }
  },
  "enrolled in": {
    "NWTC": {},
    "Western Tech": {},
    "LTC": {},
    "WTC": {},
    "NCTC": {},
    "BTC": {},
    "FVTC (Fox Valley Tech)": {},
    "Mid-State": {},
    "MATC (Madison College)": {},
    "Omega School": {},
    "Northwoods Tech": {},
    "Oneida Community Educational Center": {},
    "Medford Adult Diploma Academy": {},
    "ADVOCAP": {},
    "ADRC": {},
    "Kahoot.com": {},
    "ESL": {},
    "Test Prep Champions": {},
    "HSED": {
      "completed": [
        "HSED - TABE",
        "HSED - GED.com account",
        "HSED - Career Assessment",
        "HSED - Orientation",
        "HSED - ROI",
        "HSED - HS Transcript",
        "HSED - Employability",
        "HSED - Health",
        "HSED - Civics",
        "HSED - RLA",
        "HSED - Social Studies",
        "HSED - Science",
        "HSED - Math",
        "HSED - 17-16",
        "HSED - Journey Letter"
      ]
    },
    "GED": {
      "completed": [
        "GED Ready - RLA",
        "GED Ready - Social Studies",
        "GED Ready - Science",
        "GED Ready - Math",
        "GED - TABE",
        "GED - GED.com account",
        "GED - Career Assessment",
        "GED - Orientation",
        "GED - ROI",
        "GED - Civics",
        "GED - RLA",
        "GED - Social Studies",
        "GED - Science",
        "GED - Math"
      ]
    }
  },
  "graduated from": [
    "NWTC",
    "Western Tech",
    "LTC",
    "WTC",
    "NCTC",
    "BTC",
    "FVTC (Fox Valley Tech)",
    "Mid-State",
    "MATC (Madison College)",
    "Omega School",
    "Northwoods Tech",
    "Oneida Community Educational Center",
    "Medford Adult Diploma Academy",
    "HSED",
    "GED",
    "ADVOCAP",
    "ADRC",
    "Kahoot.com",
    "ESL",
    "Test Prep Champions"
  ],
  "completed": [
    "TABE",
    "WOWI Career Assessment"
  ],
  "needs": [
    "money",
    "food",
    "transportation",
    "shelter",
    "legal help",
    "mental health treatment",
    "medical treatment",
    "career assessment",
    "GED.com account",
    "GED Ready - RLA",
    "GED Ready - Social Studies",
    "GED Ready - Science",
    "GED Ready - Math"
  ],
  "obtained": [
    "transcripts",
    "journey letter",
    "GED",
    "HSED"
  ],
  "inactive": [
    "W-2 Case Closed",
    "Graduated",
    "Participant Declined Assistance",
    "Participant Request (Barriers)",
    "No contact with EN for 60 days",
    "Participant request (Employment)",
    "Participant decline prior to meeting EN",
    "No show to warm hand off 3x"
  ],
  "youth": {
    "attending": [
      "Abundant Life Christian School",
      "Adams-Friendship High School",
      "Afro Urban Institute",
      "Albany High School",
      "Algoma High School",
      "Alliance High School",
      "Alma High School",
      "Almond-Bancroft High School",
      "Altoona High School",
      "Amery High School",
      "Amherst High School",
      "Antigo High School",
      "Appleton East High School",
      "Appleton North High School",
      "Appleton West High School",
      "Aquinas High School",
      "Arcadia High School",
      "Argyle High School",
      "Arrowhead High School",
      "Ashland High School",
      "Ashwaubenon High School",
      "Assumption High School",
      "Athens High School",
      "Auburndale High School",
      "Augusta High School",
      "Badger High School",
      "Baldwin-Woodville High School",
      "Bangor High School",
      "Baraboo High School",
      "Bay Port High School",
      "Bayfield High School",
      "Beaver Dam High School",
      "Belleville High School",
      "Belmont High School",
      "Beloit Memorial High School",
      "Berlin High School",
      "Big Foot High School",
      "Black River Falls High School",
      "Bonduel High School",
      "Brookfield Academy",
      "Brookfield Central High School",
      "Brookfield East High School",
      "Brown Deer High School",
      "Burlington High School",
      "Cashton High School",
      "Cedarburg High School",
      "Chetek-Weyerhaeuser High School",
      "Chilton High School",
      "Chippewa Falls High School",
      "Colby High School",
      "Columbus High School",
      "Cumberland High School",
      "D.C. Everest High School",
      "De Pere High School",
      "Deerfield High School",
      "Delavan-Darien High School",
      "Denmark High School",
      "Durand High School",
      "East Troy High School",
      "Eau Claire Memorial High School",
      "Eau Claire North High School",
      "Edgerton High School",
      "Elkhorn Area High School",
      "Ellsworth High School",
      "Evansville High School",
      "Fond du Lac High School",
      "Fort Atkinson High School",
      "Fox Valley Lutheran High School",
      "Franklin High School",
      "Germantown High School",
      "Grafton High School",
      "Green Bay East High School",
      "Green Bay Preble High School",
      "Green Bay Southwest High School",
      "Green Bay West High School",
      "Hamilton High School",
      "Hartford Union High School",
      "Holmen High School",
      "Homestead High School",
      "Hudson High School",
      "Janesville Craig High School",
      "Janesville Parker High School",
      "Kaukauna High School",
      "Kettle Moraine High School",
      "Kimberly High School",
      "La Crosse Central High School",
      "La Crosse Logan High School",
      "Lake Geneva Badger High School",
      "Lodi High School",
      "Luxemburg-Casco High School",
      "Madison East High School",
      "Madison La Follette High School",
      "Madison Memorial High School",
      "Madison West High School",
      "Marinette High School",
      "Marshfield High School",
      "McFarland High School",
      "Menasha High School",
      "Menomonee Falls High School",
      "Menomonie High School",
      "Milton High School",
      "Milwaukee Hamilton High School",
      "Milwaukee King High School",
      "Milwaukee Marshall High School",
      "Milwaukee Riverside High School",
      "Milwaukee South Division High School",
      "Milwaukee Vincent High School",
      "Neenah High School",
      "New Berlin Eisenhower High School",
      "New Berlin West High School",
      "New Richmond High School",
      "Nicolet High School",
      "Notre Dame Academy",
      "Oconomowoc High School",
      "Oregon High School",
      "Oshkosh North High School",
      "Oshkosh West High School",
      "Port Washington High School",
      "Pulaski High School",
      "Racine Case High School",
      "Racine Horlick High School",
      "Racine Park High School",
      "Reedsburg Area High School",
      "Rice Lake High School",
      "River Falls High School",
      "Sheboygan North High School",
      "Sheboygan South High School",
      "Slinger High School",
      "South Milwaukee High School",
      "Sparta High School",
      "Stevens Point High School",
      "Stoughton High School",
      "Sun Prairie East High School",
      "Sun Prairie West High School",
      "Superior High School",
      "Tomah High School",
      "Two Rivers High School",
      "Union Grove High School",
      "Watertown High School",
      "Waukesha North High School",
      "Waukesha South High School",
      "Waukesha West High School",
      "Waunakee High School",
      "Waupaca High School",
      "Waupun High School",
      "Wausau East High School",
      "Wausau West High School",
      "West Allis Central High School",
      "West Bend East High School",
      "West Bend West High School",
      "West De Pere High School",
      "West Salem High School",
      "Whitewater High School",
      "Whitnall High School",
      "Wisconsin Dells High School",
      "Wisconsin Rapids Lincoln High School",
      "Xavier High School"
    ],
    "referred to": [
      "Work program",
      "Apprenticeship",
      "Tech school",
      "Tutoring",
      "University"
    ],
    "enrolled in": [
      "Work program",
      "Apprenticeship",
      "Tech school",
      "Tutoring",
      "University"
    ],
    "grade advancement": [
      "6th",
      "7th",
      "8th",
      "9th",
      "10th",
      "11th",
      "12th",
      "Graduated"
    ],
    "support service": [
      "School shoes",
      "School clothes",
      "School supplies",
      "Personal care items",
      "Drivers Education",
      "Winter gear",
      "Winter boots",
      "Sport fee",
      "Sport shoes",
      "Sport gear",
      "School fees",
      "Graduation fees",
      "Other"
    ],
    "completed": [
      "driver's education",
      "other"
    ]
  }
}
